### ISSUE TITLE
Cannot build project

### ISSUE THREAD

**Issue by andyhot** [gte451f/ember-cli-table-pagination#31]
From a fresh checkout, running `ember build` results in:

```
[ember-runtime-enumerable-includes-polyfill] Cannot identify Ember version to determine if polyfill is needed.
Cannot find module '/home/andyhot/projects/js/ember-cli-table-pagination/bower_components/ember/ember-template-compiler'
Error: Cannot find module '/home/andyhot/projects/js/ember-cli-table-pagination/bower_components/ember/ember-template-compiler'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.makeCacheKey (/home/andyhot/projects/js/ember-cli-table-pagination/node_modules/ember-cli-htmlbars-inline-precompile/lib/ast-plugins.js:64:5)
    at Class.included (/home/andyhot/projects/js/ember-cli-table-pagination/node_modules/ember-cli-htmlbars-inline-precompile/index.js:77:35)
    at Class.superWrapper [as included] (/home/andyhot/projects/js/ember-cli-table-pagination/node_modules/core-object/lib/assign-properties.js:34:20)
    at EmberAddon.<anonymous> (/home/andyhot/projects/js/ember-cli-table-pagination/node_modules/ember-cli/lib/broccoli/ember-app.js:529:17)
    at Array.filter (native)
    at EmberAddon._notifyAddonIncluded (/home/andyhot/projects/js/ember-cli-table-pagination/node_modules/ember-cli/lib/broccoli/ember-app.js:526:47)
```

**Comment by andyhot** [comment]
Since there's no bower any more, perhaps some dependency is missing. I don't see ember-source. Also, is ember-data really needed?

**Comment by brisc** [comment]
now, ember-data is used during tests. I've fixed the dependencies
